id: I761C7980
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-29T17:28:57+00:00'
last_modified: '2022-06-08T01:48:43.392031+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W3CN8387
  title: བོད་ཀྱི་ལེགས་བཤད།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    0A97:
      image_group_id: I3CN8389
      title: ''
      total_pages: 268
      order: 1
      base_file: 0A97.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
