id: P004541
initial_creation_type: ocr
source_metadata:
  id: bdr:W3CN8387
  title: བོད་ཀྱི་ལེགས་བཤད།
  author: ''
  volumes:
    ff7f4e8c84024bbda74107b100de8561:
      image_group_id: I3CN8389
      title: ''
      volume_number: 1
      total_pages: 268
      base_file: v001.txt
